version: '3.8'

services:
  postgres:
    image: postgres
    container_name: pg-py-pos
    environment:
      POSTGRES_DB: pos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pos"]
      interval: 30s
      timeout: 10s
      retries: 3