"""Add unique constraint to companies.tenant_id for 1:1 relationship

Revision ID: c49f032a791c
Revises: d01abacc144c
Create Date: 2025-12-10 22:55:32.408379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c49f032a791c'
down_revision: Union[str, Sequence[str], None] = 'd01abacc144c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Relación 1:1 con Tenant - Cada company tiene un único tenant',
               existing_comment='Tenant al que pertenece la compañía',
               existing_nullable=False)
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_tenant_id'), table_name='companies')
    op.create_index(op.f('ix_companies_tenant_id'), 'companies', ['tenant_id'], unique=False)
    op.alter_column('companies', 'tenant_id',
               existing_type=sa.UUID(),
               comment='Tenant al que pertenece la compañía',
               existing_comment='Relación 1:1 con Tenant - Cada company tiene un único tenant',
               existing_nullable=False)
    # ### end Alembic commands ###
